# https://travis-ci.org/patflick/mxx

language: cpp

sudo: required

compiler:
    - gcc
    - clang

env:
    - MPI=mpich3
    - MPI=mpich2
    - MPI=openmpi
    - MPI=openmpi18

before_install:
    - sh ./conf/travis-install-mpi.sh $MPI
    - pip install --user codecov

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

before_script:
    - ls -r $HOME/local
    - export PATH=$PATH:$HOME/local/bin
    - export LIBRARY_PATH=$LIBRARY_PATH:$HOME/local/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib
    - $CXX --version
    - mpiexec --version
    - mkdir build
    - cd build
    - cmake -DENABLE_COVERAGE=ON -DMPI_C_COMPILER=$HOME/local/bin/mpicc -DMPI_CXX_COMPILER=$HOME/local/bin/mpicxx ../

script:
    - make
    - mpiexec -np 1 ./bin/test-all
    - mpiexec -np 4 ./bin/test-all
      #- mpiexec -np 13 ./bin/test-all # fails for openmpi!! MPI_Allgather()
    - mpiexec -np 8 ./bin/test-all

after_success:
    - codecov --gcov-exec gcov-4.8
