# https://travis-ci.org/patflick/mxx

language: cpp

sudo: false

compiler:
    - gcc
    - clang

# TODO: mpich 2, OpenMPI 1.10
env:
    - MPI=mpich3
    - MPI=openmpi16
    - MPI=openmpi18

matrix:
  include:
    - env: MPI=mpich2
      addons:
        apt:
          packages:
            - gfortran mpich2 libmpich2-3 libmpich2-dev

before_install:
    - mkdir -p $HOME/local
    - sh ./conf/travis-install-mpi.sh $MPI
    - pip install --user codecov

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

cache:
  directories:
    - $HOME/local

before_script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - ls -r $HOME/local
    - export PATH=$PATH:$HOME/local/bin
    - export LIBRARY_PATH=$LIBRARY_PATH:$HOME/local/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib
    - $CXX --version
    - mpiexec --version
    - mkdir build
    - cd build
    - if [ "$MPI" = "mpich2" ]; then
      cmake -DENABLE_COVERAGE=ON ../;
      else cmake -DENABLE_COVERAGE=ON -DMPI_C_COMPILER=$HOME/local/bin/mpicc -DMPI_CXX_COMPILER=$HOME/local/bin/mpicxx ../; fi

script:
    - make
    - mpiexec -np 1 ./bin/test-all
    - mpiexec -np 4 ./bin/test-all
      #- mpiexec -np 13 ./bin/test-all # fails for openmpi!! MPI_Allgather()
    - mpiexec -np 13 ./bin/test-all

after_success:
  # only collect coverage if compiled with gcc
  - if [ "$CXX = "g++-4.8" ]; then codecov --gcov-exec gcov-4.8; fi
